version: '3.7'
services:
  arangodb_db_container:
    hostname: arangodb_db_container
    image: arangodb:latest
    environment:
      ARANGO_ROOT_PASSWORD: Blogchain
    expose:
      - 8529
    ports:
      - 8529:8529
    volumes:
      - arangodb_data_container:/var/lib/arangodb3
      - arangodb_apps_data_container:/var/lib/arangodb3-apps

  server:
    hostname: federated_server
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    environment:
      - MIN_CLIENTS=3
    expose:
      - 8080

  client-0:
    build:
      context: .
      dockerfile: ./docker/client/Dockerfile
    environment:
      - DB_NAME=Transactions0
    volumes:
      - ./data_0.csv:/data/data.csv
    depends_on:
      - arangodb_db_container

  client-1:
    build:
      context: .
      dockerfile: ./docker/client/Dockerfile
    environment:
      - DB_NAME=Transactions1
    volumes:
      - ./data_1.csv:/data/data.csv
    depends_on:
      - arangodb_db_container

  client-2:
    build:
      context: .
      dockerfile: ./docker/client/Dockerfile
    environment:
      - DB_NAME=Transactions2
    volumes:
      - ./data_2.csv:/data/data.csv
    depends_on:
      - arangodb_db_container

volumes:
  arangodb_data_container:
  arangodb_apps_data_container:
