version: '3.7'
services:
  arangodb_db_container:
    hostname: arangodb_db_container
    image: arangodb:latest
    environment:
      ARANGO_ROOT_PASSWORD: Blogchain
    expose:
      - 8529
    ports:
      - 8529:8529
    volumes:
      - arangodb_data_container:/var/lib/arangodb3
      - arangodb_apps_data_container:/var/lib/arangodb3-apps

  db_importer:
    build: .
    volumes:
      - ./data_0.csv:/data/data_0.csv
    depends_on:
      - arangodb_db_container

  server:
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile

  client:
    build:
      context: .
      dockerfile: ./docker/client/Dockerfile

volumes:
  arangodb_data_container:
  arangodb_apps_data_container:
